version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgres:12.0
    environment:
      - POSTGRES_USER=restapi
      - POSTGRES_PASSWORD=password
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U faceoff"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
    network_mode: "bridge"

volumes:
  postgres:
    name: restapi_postgres
